# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: poatmeal <poatmeal@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/08 14:27:48 by poatmeal          #+#    #+#              #
#    Updated: 2019/09/08 15:02:13 by poatmeal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = ft_display_file.c

NAME = ft_display_file

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRCS)

clean:
	rm -rf *.o

fclean: clean
	rm -rf $(NAME)
